### ISSUE TITLE
To add clarity

### ISSUE THREAD

**Issue by gb23** [learn-co-curriculum/js-templates-template-engines-readme#2]
In the prior lesson, we did not need the ```return false;``` in the form onsubmit value.  It would improve the lesson by adding clarity (and tying into previously acquired knowledge) if you explained that this return false is doing something similar to the event.preventDefault() of the prior lesson.

**Comment by cjbrock** [comment]
Hi @gb23! Thanks for your feedback. We're currently working on a revision of the JavaScript section and will take your feedback into account.

// Corinna
