### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by logemerson** [learn-co-curriculum/js-templates-template-engines-readme#3]
<img width="871" alt="screen shot 2017-11-10 at 3 56 06 pm" src="https://user-images.githubusercontent.com/28125427/32678278-bcb2fd4a-c62f-11e7-9af1-978ca625441e.png">

"delimeters" ==> delimiters

**Comment by cjbrock** [comment]
Mildly mortifying, especially since we spelled it correctly a bunch below. Thank you so much for catching that for us! Fixed now. 

// <3 Corinna
