### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by JuanGongora** [learn-co-curriculum/js-templates-template-engines-readme#6]
Simple typo on line 20 of README.md:

`The better way is to use a _template_ that provides a way to **use** dynamically add data on a set HTML structure, preventing us`

Should be:

`The better way is to use a _template_ that provides a way to dynamically add data on a set HTML structure, preventing us`

**Comment by drakeltheryuujin** [comment]
Hi @JuanGongora 
We have updated the materials and believe your issue to have been resolved.
